#!/usr/bin/env bash
# Write the licenses of the libraries shipped inside the app to
# THIRD-PARTY-NOTICES.txt. Run by `pnpm notices`. Run it again and commit the
# result whenever a dependency is added or updated (the Rust tests in
# src-tauri/src/lib.rs fail when the file is out of date).
#
# Rust: cargo-about (`cargo install cargo-about --locked --features cli`),
# configured by src-tauri/about.toml and formatted by src-tauri/about.hbs.
#
# JavaScript: only the packages that vite bundles into the web view. That is not
# the `dependencies` of package.json here: @tailwindcss/vite is a build tool,
# the @tauri-apps/plugin-* packages are not imported by the front end, and the
# SvelteKit runtime comes from devDependencies. The list below was taken from the
# modules in the client bundle of `pnpm build` (svelte, @sveltejs/kit, esm-env
# and @tauri-apps/api) plus tailwindcss, whose preflight CSS is in the built
# stylesheet. Update it when the front end starts importing another package.
set -euo pipefail

cd "$(dirname "$0")/.."

OUT="THIRD-PARTY-NOTICES.txt"
NPM_PACKAGES="@sveltejs/kit @tauri-apps/api esm-env svelte tailwindcss"

if ! cargo about --version >/dev/null 2>&1; then
  echo "Error: cargo-about is not installed. Run: cargo install cargo-about --locked --features cli" >&2
  exit 1
fi
if [ ! -d node_modules ]; then
  echo "Error: node_modules is missing. Run: pnpm install" >&2
  exit 1
fi

# Written next to the output: a mv from /tmp on another file system is a copy,
# and a copy cut short would leave a broken file behind
TMP=$(mktemp "${OUT}.XXXXXX")
trap 'rm -f "$TMP"' EXIT

{
  cat <<'HEADER'
THIRD-PARTY NOTICES

clipboard-palette bundles the open source libraries listed below. Each entry
gives the license, the packages it applies to, and the license text as shipped
by the package. Generated by scripts/generate-third-party-notices.sh; do not
edit by hand.

################################################################################
# JavaScript packages (bundled into the web view)
################################################################################

HEADER

  NPM_PACKAGES="$NPM_PACKAGES" node - <<'NODE'
const fs = require("fs");
const path = require("path");
const names = process.env.NPM_PACKAGES.split(" ").filter(Boolean);
// pnpm links only the direct dependencies into node_modules. A transitive one
// (esm-env) sits next to the package that depends on it, so look there too
function findPackage(name) {
  const candidates = [path.join("node_modules", name)];
  for (const other of names) {
    const top = path.join("node_modules", other);
    if (!fs.existsSync(top)) continue;
    const real = fs.realpathSync(top);
    const root = real.slice(0, real.lastIndexOf(`${path.sep}node_modules${path.sep}`) + 13);
    candidates.push(path.join(root, name));
  }
  const found = candidates.find((dir) => fs.existsSync(path.join(dir, "package.json")));
  if (!found) throw new Error(`${name} is not installed; run pnpm install`);
  return found;
}
for (const name of [...names].sort()) {
  const dir = findPackage(name);
  const pkg = JSON.parse(fs.readFileSync(path.join(dir, "package.json"), "utf8"));
  const repo = typeof pkg.repository === "string" ? pkg.repository : pkg.repository?.url;
  // SPDX metadata such as LICENSE.spdx is not the license text
  const files = fs
    .readdirSync(dir)
    .filter((f) => /^(LICEN[CS]E|COPYING|NOTICE)/i.test(f) && !/\.spdx$/i.test(f))
    .sort();
  console.log("=".repeat(80));
  console.log(`License: ${pkg.license}`);
  console.log("");
  console.log("Used by:");
  console.log(`  ${name} ${pkg.version}${repo ? ` (${repo})` : ""}`);
  console.log("");
  if (files.length === 0) {
    // The package does not ship its license text; keep the notice and the source
    console.log("The package does not ship its license text; see the repository above.");
    console.log("");
    continue;
  }
  for (const f of files) {
    if (files.length > 1) console.log(`--- ${f} ---`);
    console.log(fs.readFileSync(path.join(dir, f), "utf8").replace(/\s+$/, ""));
    console.log("");
  }
}
NODE

  cat <<'HEADER'
################################################################################
# Rust crates (compiled into the binary)
################################################################################

HEADER

  # --fail: a crate whose license cannot be determined fails the run instead of
  # being dropped with a warning
  cargo about generate --manifest-path src-tauri/Cargo.toml --locked --fail src-tauri/about.hbs
} > "$TMP"

mv "$TMP" "$OUT"
trap - EXIT
echo "Wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
