//! Third-party license notices: the text shown by `--license` and by the
//! "Third-Party Licenses" menu item.
//!
//! THIRD-PARTY-NOTICES.txt at the repository root is generated by
//! scripts/generate-third-party-notices.sh (`pnpm notices`) and compiled into
//! the binary, so the app never reads the repository at run time.

use tauri::menu::{Menu, MenuItem, HELP_SUBMENU_ID};
use tauri::{AppHandle, Manager, Runtime, Theme, WebviewUrl, WebviewWindowBuilder};

/// The app's own license (MIT).
const LICENSE: &str = include_str!("../../LICENSE");

/// Licenses of the libraries shipped inside the app.
pub const THIRD_PARTY_NOTICES: &str = include_str!("../../THIRD-PARTY-NOTICES.txt");

/// Menu item id of "Third-Party Licenses".
pub const LICENSES_MENU_ID: &str = "third-party-licenses";

/// Label of the window that shows the notices.
const LICENSES_WINDOW_LABEL: &str = "licenses";

/// What `--license` prints: the app's own license, then the notices.
pub fn license_text() -> String {
    format!("clipboard-palette\n\n{LICENSE}\n\n{THIRD_PARTY_NOTICES}")
}

#[tauri::command]
pub fn third_party_notices() -> &'static str {
    THIRD_PARTY_NOTICES
}

/// The default menu with "Third-Party Licenses" right below About.
///
/// On macOS About is the first item of the app menu. Elsewhere the default menu
/// keeps About in the Help menu. Only registered on macOS (the only platform the
/// app is released for), so other platforms keep running without a menu bar.
#[cfg_attr(not(target_os = "macos"), allow(dead_code))]
pub fn app_menu<R: Runtime>(app: &AppHandle<R>) -> tauri::Result<Menu<R>> {
    let menu = Menu::default(app)?;
    let licenses = MenuItem::with_id(
        app,
        LICENSES_MENU_ID,
        "Third-Party Licenses",
        true,
        None::<&str>,
    )?;
    let about_menu = if cfg!(target_os = "macos") {
        menu.items()?.into_iter().next()
    } else {
        menu.get(HELP_SUBMENU_ID)
    };
    match about_menu.as_ref().and_then(|item| item.as_submenu()) {
        Some(submenu) => submenu.insert(&licenses, 1)?,
        None => menu.append(&licenses)?,
    }
    Ok(menu)
}

/// Show the Third-Party Licenses window, or bring it to the front if it is
/// already open. It is destroyed when closed.
///
/// `init_script` and `theme` carry --theme, the same way the main window gets
/// them, so the content and the title bar do not fall back to the OS theme.
pub fn show_licenses_window<R: Runtime>(
    app: &AppHandle<R>,
    init_script: String,
    theme: Option<Theme>,
) -> tauri::Result<()> {
    if let Some(window) = app.get_webview_window(LICENSES_WINDOW_LABEL) {
        window.show()?;
        return window.set_focus();
    }
    // The prerendered SvelteKit route src/routes/licenses (build/licenses.html)
    WebviewWindowBuilder::new(
        app,
        LICENSES_WINDOW_LABEL,
        WebviewUrl::App("licenses".into()),
    )
    .title("Third-Party Licenses")
    .inner_size(640.0, 560.0)
    .min_inner_size(400.0, 300.0)
    .center()
    .initialization_script(init_script)
    .theme(theme)
    .build()?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{license_text, THIRD_PARTY_NOTICES};

    /// Windows checkouts turn these files into CRLF (autocrlf), so line ends are
    /// normalised before anything is searched for.
    fn lf(text: &str) -> String {
        text.replace("\r\n", "\n")
    }

    /// Names of the shipped direct dependencies in Cargo.toml: `[dependencies]`
    /// and `[target.'cfg(..)'.dependencies]`, one-line `name = ...` entries only.
    /// Build and dev dependencies do not end up in the app.
    fn direct_rust_dependencies(manifest: &str) -> Vec<String> {
        let mut section = String::new();
        let mut names = Vec::new();
        for line in manifest.lines() {
            let line = line.trim();
            if line.starts_with('[') {
                section = line.to_string();
                continue;
            }
            let shipped = section == "[dependencies]"
                || (section.starts_with("[target.") && section.ends_with(".dependencies]"));
            if !shipped || line.starts_with('#') {
                continue;
            }
            if let Some((name, _)) = line.split_once('=') {
                names.push(name.trim().to_string());
            }
        }
        names
    }

    /// The (name, version) pairs under the "Used by:" blocks of one section of
    /// THIRD-PARTY-NOTICES.txt. A block is a separator line, `License: ...`, an
    /// empty line and "Used by:", so the same words inside a license text are
    /// not counted.
    fn packages_in_notices(notices: &str, section: &str) -> Vec<(String, String)> {
        let text = match section {
            "npm" => notices.split("# Rust crates").next(),
            "rust" => notices.split("# Rust crates").nth(1),
            _ => None,
        }
        .expect("the notices file has a Rust crates heading");
        let separator = "=".repeat(80);
        let mut packages = Vec::new();
        let mut in_block = false;
        let mut after_separator = false;
        let mut after_license = false;
        for line in text.lines() {
            if in_block {
                let mut words = line.strip_prefix("  ").unwrap_or("").split(' ');
                match (words.next(), words.next()) {
                    (Some(name), Some(version)) if !name.is_empty() => {
                        packages.push((name.to_string(), version.to_string()));
                    }
                    _ => in_block = false,
                }
                continue;
            }
            in_block = after_license && line == "Used by:";
            after_license = (after_separator && line.starts_with("License: "))
                || (after_license && line.is_empty());
            after_separator = line == separator;
        }
        packages
    }

    /// The [[package]] blocks of Cargo.lock: (name, version, dependency lines).
    fn locked_rust_packages(lock: &str) -> Vec<(String, String, Vec<String>)> {
        lock.split("[[package]]")
            .skip(1)
            .map(|block| {
                let field = |key: &str| {
                    block
                        .lines()
                        .find_map(|line| line.strip_prefix(key))
                        .map(|rest| rest.trim().trim_matches('"').to_string())
                        .unwrap_or_default()
                };
                let deps = block
                    .lines()
                    .filter_map(|line| line.strip_prefix(" \""))
                    .map(|line| line.trim_end_matches("\",").to_string())
                    .collect();
                (field("name = "), field("version = "), deps)
            })
            .collect()
    }

    /// The version Cargo.lock picked for the direct dependency `name`. When a
    /// crate is in the lock at several versions, the root lists it as
    /// `name version`.
    fn resolved_rust_version(lock: &[(String, String, Vec<String>)], name: &str) -> String {
        let root = lock
            .iter()
            .find(|(crate_name, _, _)| crate_name == "clipboard-palette")
            .expect("Cargo.lock has the clipboard-palette package");
        let entry = root
            .2
            .iter()
            .find(|dep| *dep == name || dep.starts_with(&format!("{name} ")))
            .unwrap_or_else(|| panic!("{name} is not a dependency of clipboard-palette"));
        match entry.split(' ').nth(1) {
            Some(version) => version.to_string(),
            None => {
                let mut versions = lock
                    .iter()
                    .filter(|(crate_name, _, _)| crate_name == name)
                    .map(|(_, version, _)| version.clone());
                let version = versions.next().expect("the crate is in Cargo.lock");
                assert!(
                    versions.next().is_none(),
                    "{name} has several versions in Cargo.lock"
                );
                version
            }
        }
    }

    /// The (name, version) of every direct dependency of the project in
    /// pnpm-lock.yaml (`importers` -> `.`), dependencies and devDependencies
    /// alike: the bundled SvelteKit runtime comes from devDependencies.
    fn resolved_npm_versions(lock: &str) -> Vec<(String, String)> {
        let importer = lock
            .split("\nimporters:\n")
            .nth(1)
            .expect("pnpm-lock.yaml has an importers section")
            .split("\npackages:\n")
            .next()
            .expect("importers come before packages");
        let mut resolved = Vec::new();
        let mut name = String::new();
        for line in importer.lines() {
            if let Some(key) = line
                .strip_prefix("      ")
                .filter(|rest| !rest.starts_with(' '))
            {
                name = key.trim_end_matches(':').trim_matches('\'').to_string();
            } else if let Some(version) = line.strip_prefix("        version: ") {
                // Peer dependencies in parentheses are not part of the version
                let version = version.split('(').next().unwrap_or(version).trim();
                resolved.push((name.clone(), version.to_string()));
            }
        }
        resolved
    }

    /// Whether pnpm-lock.yaml has `name@version` in its packages section.
    fn npm_package_is_locked(lock: &str, name: &str, version: &str) -> bool {
        let key = format!("{name}@{version}:");
        lock.lines().any(|line| {
            let line = line.trim();
            line == key || line == format!("'{name}@{version}':")
        })
    }

    /// Every shipped direct dependency is listed at the version Cargo.lock
    /// picked. Checking names alone would pass when an updated dependency's old
    /// version is still in the tree as a transitive one.
    #[test]
    fn third_party_notices_list_every_direct_rust_dependency() {
        // Arrange
        let deps = direct_rust_dependencies(&lf(include_str!("../Cargo.toml")));
        assert!(deps.contains(&"tauri".to_string()), "parsed deps: {deps:?}");
        let lock = locked_rust_packages(&lf(include_str!("../Cargo.lock")));
        let listed = packages_in_notices(&lf(THIRD_PARTY_NOTICES), "rust");
        assert!(listed.len() > 100, "parsed notices: {listed:?}");

        // Act
        let missing: Vec<(String, String)> = deps
            .iter()
            .map(|name| (name.clone(), resolved_rust_version(&lock, name)))
            .filter(|entry| !listed.contains(entry))
            .collect();

        // Assert
        assert!(
            missing.is_empty(),
            "not in THIRD-PARTY-NOTICES.txt (run `pnpm notices`): {missing:?}"
        );
    }

    /// A listed crate whose version is not in Cargo.lock means a dependency was
    /// updated without running `pnpm notices`.
    #[test]
    fn third_party_notices_match_cargo_lock_versions() {
        // Arrange
        let lock = locked_rust_packages(&lf(include_str!("../Cargo.lock")));
        let listed = packages_in_notices(&lf(THIRD_PARTY_NOTICES), "rust");
        assert!(listed.len() > 100, "parsed notices: {listed:?}");

        // Act
        let stale: Vec<&(String, String)> = listed
            .iter()
            .filter(|(name, version)| !lock.iter().any(|(n, v, _)| n == name && v == version))
            .collect();

        // Assert
        assert!(
            stale.is_empty(),
            "not in Cargo.lock (run `pnpm notices`): {stale:?}"
        );
    }

    /// The listed npm packages are the versions pnpm-lock.yaml installs, and
    /// the ones the project depends on directly are at the version it picked.
    /// The npm side is read from node_modules, so updating the lock without
    /// installing and regenerating leaves the old versions behind.
    #[test]
    fn third_party_notices_match_pnpm_lock_versions() {
        // Arrange
        let lock = lf(include_str!("../../pnpm-lock.yaml"));
        let direct = resolved_npm_versions(&lock);
        assert!(
            direct.iter().any(|(name, _)| name == "svelte"),
            "parsed lock importer: {direct:?}"
        );
        let listed = packages_in_notices(&lf(THIRD_PARTY_NOTICES), "npm");
        assert!(
            listed.iter().any(|(name, _)| name == "@tauri-apps/api"),
            "parsed notices: {listed:?}"
        );

        // Act
        let stale: Vec<&(String, String)> = listed
            .iter()
            .filter(|(name, version)| {
                let direct_mismatch = direct.iter().any(|(n, v)| n == name && v != version);
                direct_mismatch || !npm_package_is_locked(&lock, name, version)
            })
            .collect();

        // Assert
        assert!(
            stale.is_empty(),
            "not what pnpm-lock.yaml installs (run `pnpm install` and `pnpm notices`): {stale:?}"
        );
    }

    /// Same results on a Windows (CRLF) checkout.
    #[test]
    fn notices_parsers_accept_crlf() {
        // Arrange
        let notices = "x\r\n# Rust crates\r\n\r\n".to_string()
            + &"=".repeat(80)
            + "\r\nLicense: MIT\r\n\r\nUsed by:\r\n  serde 1.0.0 (u)\r\n\r\ntext\r\n";
        let lock = "lockfileVersion: '9.0'\r\nimporters:\r\n  .:\r\n    dependencies:\r\n      svelte:\r\n        specifier: ^5\r\n        version: 5.0.0\r\npackages:\r\n";

        // Act
        let listed = packages_in_notices(&lf(&notices), "rust");
        let resolved = resolved_npm_versions(&lf(lock));

        // Assert
        assert_eq!(listed, vec![("serde".to_string(), "1.0.0".to_string())]);
        assert_eq!(resolved, vec![("svelte".to_string(), "5.0.0".to_string())]);
    }

    #[test]
    fn license_text_holds_the_app_license_and_the_notices() {
        // Act
        let text = license_text();

        // Assert
        assert!(text.contains("MIT License"), "{}", &text[..200]);
        assert!(text.contains("Copyright (c) 2026 ytyng"));
        assert!(text.contains("THIRD-PARTY NOTICES"));
        assert!(text.contains("# Rust crates (compiled into the binary)"));
    }
}
